# Generated by Django 2.2.1 on 2019-05-08 17:00

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='content',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True),
        ),
    ]
