# Generated by Django 2.2.1 on 2019-05-08 17:35

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190508_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
