# Generated by Django 2.1.3 on 2018-11-29 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_remove_startup_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='startup',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_startup_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='startup',
            name='owner',
        ),
        migrations.AddField(
            model_name='startup',
            name='owner',
            field=models.ManyToManyField(related_name='owner_startup_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
