# Generated by Django 2.1.3 on 2018-11-29 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0006_auto_20181129_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='employee',
        ),
        migrations.AddField(
            model_name='startup',
            name='employee',
            field=models.ManyToManyField(related_name='employee_startup_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
