# Generated by Django 2.1.3 on 2018-11-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_startup_perma'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='lastChange',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
