# Generated by Django 2.1.3 on 2018-11-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_startup_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='members',
        ),
    ]
