# Generated by Django 2.1.3 on 2018-11-29 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0007_auto_20181129_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_project_set', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ManyToManyField(related_name='employee_project_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
