# Generated by Django 2.1.3 on 2018-11-29 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0008_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='startup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='startup_project_set', to='notes.Startup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='founder',
            field=models.ManyToManyField(related_name='founder_startup_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
