# Generated by Django 2.1.3 on 2018-11-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20181129_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='perma',
            field=models.CharField(default='FrozenForest', max_length=50),
            preserve_default=False,
        ),
    ]
