# Generated by Django 2.1.3 on 2018-12-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_auto_20181201_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='perma',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
